version: '3.8'

services:
  todo:
    build: .
    restart: always 
    container_name: todo-app
    depends_on:
      - db
      - minio
    networks:
      - todonet
    ports:
      - "4853:4853"

  db:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPass
      - POSTGRES_DB=todo
    networks:
      - todonet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: todo-minio
    environment:
      - MINIO_ROOT_USER=mys3accesskey
      - MINIO_ROOT_PASSWORD=mys3secretkey
    command: server /data --console-address ":9001"
    networks:
      - todonet
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:

networks:
  todonet:
