Server:
  Address: "0.0.0.0"
  Port: "4853"

Postgres:
  Host: "db"
  Port: "5432"
  Username: "postgres"
  Password: "postgresPass"
  Name: "todo"
  Driver: "postgres"
  IsMock: false

Storage:
  Endpoint: "minio:9000"
  Bucket: "todo"
  AccessKey: "mys3accesskey"
  SecretKey: "mys3secretkey"
  MaxFileSize: 500000
  IsMock: false

SQS:
  IsMock: true
  AccessKey: "some access key"
  SecretKey: "some super secret key"
  QueueUrl: "my queue url"
