Server:
  Address: "localhost"
  Port: "4853"

Postgres:
  Host: "localhost"
  Port: "5432"
  Username: "postgres"
  Password: "postgresPass"
  Name: "todo"
  Driver: "postgres"

Storage:
  Endpoint: "http://localhost:9000"
  Bucket: "todo"
  AccessKey: "OyOKCJcBx3aW05nF9ttl"
  SecretKey: "ffDIi3eBb8wOOhfamPcjr05gNKj3R3tXywc6enUP"
